project:
  type: website
  output-dir: docs

website:
  title: "Kartikeya's Musings"
  navbar:
    left:
      - href: blog/blog.qmd
        text: Blog
      - about.qmd

format:
  html:
    theme: journal 
    css: styles.css
    toc: true



